version: '2.6'

services:
  db:
    image: postgres:14.1
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: starburger_db

  frontend:
    volumes:
      - static:/app/bundles
    build:
     context: .
     dockerfile: Dockerfile_frontend
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    container_name: starburger_frontend

  backend:
    volumes:
      - static:/app/staticfiles
      - static:/app/bundles
      - media:/app/media
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile_backend
    command: >
        sh -c "python manage.py collectstatic --no-input
        && python manage.py migrate
        && gunicorn -w 3 -b 0.0.0.0:8080 star_burger.wsgi:application"
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - db
    restart: always
    container_name: starburger_backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/app/staticfiles
      - media:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - backend
    container_name: starburger_nginx

volumes:
  static:
  media:
  postgres_data:
