# Generated by Django 3.2.15 on 2023-01-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_ordercomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='фамилия покупателя'),
        ),
    ]
