# Generated by Django 3.2.15 on 2023-01-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_adress_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='ordercomponent',
            old_name='amount',
            new_name='quantity',
        ),
    ]
