# Generated by Django 3.2.15 on 2023-01-28 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230128_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomponent',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
