# Generated by Django 3.2.15 on 2023-02-09 15:18

from django.db import migrations
from django.db.models import Subquery, OuterRef


def set_component_price(apps, schema_editor):
    OrderComponent = apps.get_model('foodcartapp', 'OrderComponent')
    Product = apps.get_model('foodcartapp', 'Product')
    products_subquery = Product.objects.filter(id=OuterRef('product_id'))
    OrderComponent.objects.filter(price=0).update(
        price=Subquery(products_subquery.values('price')[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_ordercomponent_price'),
    ]

    operations = [
        migrations.RunPython(set_component_price)
    ]
