# Generated by Django 3.2.15 on 2023-02-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230209_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CONFIRM', 'Ожидает подтверждения'), ('PREPARE', 'Готовится'), ('DELIVER', 'Передан курьеру'), ('FINISH', 'Выполнен')], db_index=True, default='CONFIRM', max_length=7, verbose_name='статус заказа'),
        ),
    ]
