# Generated by Django 3.2.15 on 2023-02-11 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_dateitme',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Подтвержден'),
        ),
        migrations.AddField(
            model_name='order',
            name='creation_dateitme',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_dateitme',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доставлен'),
        ),
    ]
