# Generated by Django 3.2.15 on 2023-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ожидает подтверждения'), (2, 'Готовится'), (3, 'Передан курьеру'), (4, 'Выполнен')], db_index=True, default=1),
        ),
    ]
