# Generated by Django 3.2.15 on 2023-02-23 15:47

from django.db import migrations


def fix_status_values(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    new_choices = {
        'CONFIRM': 1,
        'PREPARE': 2,
        'DELIVER': 3,
        'FINISH': 4
    }
    orders = Order.objects.exclude(status__in=new_choices.values())
    for order in orders:
        order.status=new_choices.get(order.status)
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(fix_status_values)
    ]
