# Generated by Django 3.2.15 on 2023-03-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230301_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='confirmation_dateitme',
            new_name='confirmation_datetime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='creation_dateitme',
            new_name='creation_datetime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_dateitme',
            new_name='delivery_datetime',
        ),
    ]
